import type { Service, Neighborhood } from "./data";

interface MoneyPageContent {
  heroDescription: string;
  sections: { heading: string; content: string }[];
}

const serviceContent: Record<string, { projectDescription: string; sizingGuide: string; weightTips: string; bestPractices: string; whyUs: string }> = {
  "construction-dumpster-rental": {
    projectDescription: "Construction projects are among the most waste-intensive jobs in the industry. From foundation work through framing, roofing, drywall installation, and finishing, every phase generates debris that needs to go somewhere. Lumber cutoffs, drywall scraps, concrete waste, metal flashing, packaging materials, and general job site debris accumulate fast. Without a properly sized dumpster on site, crews waste hours hauling debris to a distant container or making dump runs. A roll-off dumpster positioned right at the work area keeps your crew focused on building, not on waste management. We work with general contractors, subcontractors, and owner-builders across Florida to provide reliable dumpster service that matches the pace of construction.",
    sizingGuide: "Most residential construction jobs need a 20 yard dumpster as a baseline. For framing-only phases with mostly lumber cutoffs, a 20 yard handles a typical single-family home. Once you add drywall, roofing, and mixed debris, a 30 yard becomes the better choice. Commercial construction almost always starts at 30 yards. For long-duration builds, we set up rotation schedules — when one fills up, we swap it for an empty within hours. Multi-building projects often run 2-3 dumpsters simultaneously. The key is matching container size to the current phase of work, not trying to cover the entire project with one container.",
    weightTips: "Construction debris varies wildly in weight. Lumber scraps run about 300-500 lbs per cubic yard. Drywall comes in around 500-700 lbs per cubic yard. Concrete and masonry shoot up to 2,000-2,500 lbs per cubic yard. Roofing shingles fall in the 700-1,000 lbs per cubic yard range. If your project involves heavy materials like concrete or brick, separate them from lighter debris. Two properly loaded dumpsters cost less than one overweight dumpster with overage charges. We help you plan the weight strategy before the first shovel hits dirt.",
    bestPractices: "Position your dumpster where the most waste is generated — near the lumber staging area during framing, close to the building entrance during interior work. Keep a clear path from the work area to the dumpster. Break down oversized materials before tossing them in — flat-packing drywall scraps and cutting long lumber pieces maximizes space. Load heavy items first (concrete, tile, masonry) and lighter items on top. Close the rear swing door before throwing anything over the sides. Daily end-of-day cleanup into the dumpster keeps your site OSHA-compliant and impresses inspectors.",
    whyUs: "We built our business around contractors. That means priority scheduling when residential customers face wait times, volume pricing that saves you 15-25% on every rental, dedicated account management so you have one person who knows your projects, and NET-30 billing so you are not paying upfront for every container. Our drivers know construction sites — they can place a 30 yard dumpster with precision in tight spots, navigate around equipment, and time deliveries to avoid disrupting crane operations or concrete pours.",
  },
  "residential-dumpster-rental": {
    projectDescription: "Residential dumpster rental covers every type of home project that generates more waste than your weekly trash pickup can handle. Garage cleanouts where you finally confront years of accumulated stuff. Attic purges that unearth boxes you have not opened since you moved in. Shed demolitions that turn a rotting eyesore into usable yard space. Pre-move decluttering that saves you hundreds on moving costs by reducing your load. Basement cleanouts, yard overhauls, fence replacements, small deck removals, and the catch-all category of stuff-that-has-been-sitting-there-too-long. A dumpster in your driveway changes the psychology of cleaning — when disposing of something is as easy as walking it outside and tossing it in, you suddenly find the motivation to let go of things you have been holding onto for no reason.",
    sizingGuide: "For most residential projects, a 10 yard dumpster is all you need. It holds about 4 pickup truck loads — enough for a garage cleanout, a single room renovation, or a moderate yard cleanup. When the project scope expands to multiple rooms, a full estate cleanout, or a renovation involving drywall and flooring removal, the 20 yard becomes the right call at roughly 8 pickup truck loads. The 30 yard is rarely needed for residential unless you are doing a whole-house gut or major addition. Our recommendation: describe your project to us and we will tell you the right size. We would rather put you in a 10 yard and save you money than upsell you a 20 yard you do not need.",
    weightTips: "Residential debris is usually light relative to its volume. Furniture, clothing, cardboard boxes, old electronics, toys, kitchenware — these items fill space but do not weigh much. The exceptions are old appliances (a refrigerator weighs 200-300 lbs), mattresses (80-150 lbs but bulky), and any concrete, tile, or dirt from landscaping. Most residential cleanouts come in well under the 2-ton weight limit on a 10 yard dumpster. You would have to work hard to exceed it with household items alone.",
    bestPractices: "Start with the easiest wins — obviously broken items, empty boxes, things you forgot you owned. Build momentum before tackling sentimental items. Use the four-category method: keep, donate, sell, trash. Everything in the trash category goes straight to the dumpster. Break down furniture when possible to maximize space — remove legs from tables, disassemble bed frames, flatten cardboard boxes. Load the dumpster from back to front, distributing weight evenly. The rear swing door opens for walk-in loading of heavy items — use it instead of trying to lift heavy things over the sides.",
    whyUs: "We make residential dumpster rental simple because we know it is probably your first time. You call or text, tell us about your project, and we recommend the right size at a flat rate with no hidden fees. We deliver on your schedule, you load at your own pace, and we pick up when you are done. No pressure, no upselling, no surprise charges. If you finish early, we pick up early. If you need more time, we extend by the day. We have served thousands of homeowners across Florida and we know how to make this process painless.",
  },
  "commercial-dumpster-rental": {
    projectDescription: "Commercial dumpster rental serves businesses, property managers, retail operations, restaurants, offices, and industrial facilities that generate waste beyond what standard trash service handles. Tenant improvement buildouts that gut and rebuild commercial spaces. Shopping center renovations that update aging retail environments. Office relocations that produce mountains of old furniture, equipment, and files. Restaurant closures or remodels that strip out commercial kitchen equipment, booths, flooring, and decor. Warehouse cleanouts during business closures or relocations. Hotel renovations room by room or floor by floor. The commercial world generates waste at scale, and managing it requires a waste removal partner who understands business timelines and constraints.",
    sizingGuide: "Commercial projects typically start at 20 yards and scale up. A single office suite TI buildout might fill one 20 yard container. A full floor renovation in a commercial building needs 30 yards with rotation. Warehouse cleanouts often require multiple 30 yard containers running simultaneously. Retail renovations vary widely — a small boutique remodel fits in a 20 yard while a department store gut-and-rebuild might need continuous 30 yard rotation for weeks. We assess every commercial project individually because cookie-cutter sizing wastes your money and your time.",
    weightTips: "Commercial debris weight depends heavily on what is being removed. Office furniture and carpet are relatively light. Commercial kitchen equipment is dense stainless steel — heavy. Concrete block interior walls are extremely heavy. Commercial tile floors with thick mortar beds generate serious weight. Strip mall renovations involving multiple material types create unpredictable loads. We recommend weighing on a load-by-load basis for large commercial projects rather than guessing at a blanket weight allocation.",
    bestPractices: "Coordinate dumpster placement with building management or your landlord. Place containers at loading docks or service entrances — never at main customer-facing entrances. Schedule deliveries and pickups during off-hours if the business or neighboring tenants are still operating. Separate recyclable materials like cardboard, metal, and clean wood from general waste to reduce disposal costs. Keep fire lanes and emergency exits clear. Document placement with photos in case of any disputes with property management.",
    whyUs: "We handle commercial accounts with the professionalism your business expects. Consolidated monthly invoicing organized by location or project. Dedicated account management with a single point of contact. Priority scheduling that respects your construction timeline and business operations. Insurance certificates provided on request. We understand that commercial projects have stakeholders, deadlines, and budgets that residential projects do not — and we manage our service accordingly.",
  },
};

const defaultServiceContent = {
  projectDescription: "This type of project generates significant waste that needs professional disposal. Whether you are a homeowner tackling a DIY project, a contractor managing a job site, or a property manager overseeing maintenance, having the right dumpster on site makes the difference between an efficient project and a logistical nightmare. Roll-off dumpsters eliminate the need for multiple dump runs, keep your workspace clean and safe, and let you focus on the actual work instead of waste management. We deliver the right size container to your location, you load it at your own pace, and we haul it away when you are done.",
  sizingGuide: "Choosing the right dumpster size depends on the scope of your project and the type of materials you are disposing of. A 10 yard dumpster holds approximately 4 pickup truck loads and works well for small cleanouts, single-room renovations, and minor demolition projects. A 20 yard dumpster holds about 8 pickup truck loads and is our most popular size — it handles kitchen and bathroom renovations, roofing tear-offs, estate cleanouts, and medium-sized construction projects. A 30 yard dumpster holds roughly 12 pickup truck loads and is built for large construction, whole-house renovations, and commercial cleanouts. When in doubt, size up — the price difference between sizes is typically $50-100, while ordering a second dumpster costs $300+ extra.",
  weightTips: "Every dumpster has an included weight limit: 2 tons for 10 yard, 3 tons for 20 yard, and 4 tons for 30 yard containers. Most household and general construction debris comes in well under these limits. The materials that push you over are dense items like concrete, brick, tile, stone, dirt, and roofing shingles. If your project involves these heavy materials, let us know when you book so we can recommend the right size and set appropriate weight expectations. Separating heavy materials from lighter debris into different loads often saves money compared to one overloaded mixed container.",
  bestPractices: "Load the dumpster from back to front, placing heavy items on the bottom and lighter items on top. Break down large items to maximize space — disassemble furniture, flatten boxes, cut long boards into manageable lengths. Use the rear swing door for walk-in loading of heavy items rather than lifting them over the sides. Keep the load level and below the fill line — nothing can extend above the top of the dumpster walls. Distribute weight evenly across the container rather than piling everything on one side. Cover the dumpster with a tarp during rain to prevent water weight accumulation.",
  whyUs: "We provide flat-rate pricing with no hidden fees — the number we quote includes delivery, pickup, the rental period, and disposal up to the weight limit. Same-day delivery is available when you order before noon. Our 7-day standard rental period gives you plenty of time for most projects, and extensions are available at a reasonable daily rate. We answer our phone, we show up on time, and we do exactly what we say we will do. Our reputation across Florida is built on reliability and honesty, not on clever marketing.",
};

export function getMoneyPageContent(service: Service, neighborhood: Neighborhood): MoneyPageContent {
  const { name: sName } = service;
  const { name: nName, region } = neighborhood;
  const sLower = sName.toLowerCase();
  const sc = serviceContent[service.slug] || defaultServiceContent;

  const heroDescription = `Need ${sLower} in ${nName}? We deliver 10, 20, and 30 yard roll-off dumpsters throughout ${nName} and the ${region} area with same-day or next-day delivery. Flat-rate pricing, no hidden fees, and a 7-day rental period included with every container. Whether your project is residential, commercial, or contractor-managed, we have the right dumpster at the right price. Text or call for an instant quote.`;

  const sections: { heading: string; content: string }[] = [
    {
      heading: `About ${sName} in ${nName}`,
      content: `${sc.projectDescription} In ${nName} and throughout ${region}, we see these projects year-round. Florida's climate, growth rate, and housing stock create constant demand for dumpster service — and we are positioned to deliver fast, reliable service every time. Whether your project is on a quiet residential street in ${nName} or at a busy commercial site, we handle the waste removal so you can focus on the work.`,
    },
    {
      heading: `Choosing the Right Dumpster Size for Your ${nName} Project`,
      content: `${sc.sizingGuide} For projects in ${nName} specifically, we keep inventory staged across ${region} to ensure fast delivery of all three sizes. If you are unsure which size fits your project, text us a description or photos and we will recommend the right container. Getting the size right the first time saves you money and avoids project delays.`,
    },
    {
      heading: `Weight Limits and Heavy Materials`,
      content: sc.weightTips,
    },
    {
      heading: `How ${sName} Works in ${nName}`,
      content: `The process is straightforward. Contact us with your ${nName} delivery address, the dumpster size you need (or describe your project and we will recommend one), and your preferred delivery date. We confirm availability and give you a flat-rate quote. On delivery day, our driver places the dumpster exactly where you want it — typically on your driveway, but we can also place on streets (with permit if required), parking lots, construction pads, and other hard surfaces. You load at your own pace over the 7-day rental period. When you are done, text or call us and we schedule pickup within 24 hours. The entire process is designed to be simple, transparent, and hassle-free.`,
    },
    {
      heading: "Best Practices for Loading Your Dumpster",
      content: sc.bestPractices,
    },
    {
      heading: `Delivery and Logistics in ${nName}`,
      content: `Our delivery fleet covers all of ${region} with same-day service available for orders placed before noon. For ${nName} deliveries, our drivers are familiar with the local roads, traffic patterns, and common placement challenges. We need approximately 60 feet of straight-line approach for the roll-off truck and about 23 feet of vertical clearance for overhead wires and trees. If your driveway is narrow, curved, has a steep grade, or has low-hanging branches, let us know when you book so we can plan the best approach. We send a photo confirmation after delivery so you can verify placement even if you are not on site.`,
    },
    {
      heading: `Permits and Local Regulations in ${nName}`,
      content: `Placing a dumpster on your own private property in ${nName} generally requires no permit. If the dumpster needs to go on a public street, sidewalk, or right-of-way, you will likely need a permit from your local municipality or county. Permit requirements vary across ${region} — some areas require them for any street placement, while others are more relaxed. Costs typically range from $25 to $150 with 1-3 business day processing. When you give us your delivery address, we will tell you exactly what is required and can guide you through the process. We have placed dumpsters in every part of ${region} and know the local rules.`,
    },
    {
      heading: `Flat-Rate Pricing in ${nName}`,
      content: `Every dumpster rental in ${nName} includes flat-rate pricing: delivery, a 7-day rental period, pickup, and disposal up to the included weight limit — all in one price. There is no separate delivery fee, fuel surcharge, environmental fee, or pickup charge. Our 10 yard dumpsters start at $275, 20 yard at $350, and 30 yard at $450. Exact pricing depends on your specific location within ${region} and the type of debris you are disposing of. The quote we give you is the price on your invoice, guaranteed. The only potential additional charge is a per-ton overage fee if your load exceeds the included weight limit — and we help you avoid that by recommending the right size for your project.`,
    },
    {
      heading: `Why ${nName} Customers Choose Us`,
      content: sc.whyUs,
    },
    {
      heading: `What Can Go in Your Dumpster in ${nName}`,
      content: `Accepted materials include household furniture, appliances (refrigerant must be removed from fridges and AC units), drywall, lumber, roofing shingles, concrete, brick, tile, carpet, vinyl flooring, yard waste, cardboard, general junk, and most construction and demolition debris. Prohibited materials include hazardous waste, asbestos, liquid paint, chemicals, pesticides, propane tanks, batteries, medical waste, and tires in quantities over four. These restrictions are set by Florida state law and landfill regulations — they apply everywhere in ${region}, not just in ${nName}. If you are unsure about a specific item, text us a photo and we will confirm immediately.`,
    },
  ];

  return { heroDescription, sections };
}
